
        <div class="page-header">
          <h2>Contact US</h2>
        </div>
        <p class="lead" style="text-align:justify;">We welcome (on all fronts) participation in the beautiful-data project.  We're always looking for data science fanatics regardless of their background.  Alternatively, if your organization is in need of a tool for big data work, please also let us know how we can help.</p>
        
        <p>For more information on BD and how you can help us grow or how we can help your organization, please send email to <a href="mailto:johnjtran@acm.org">johnjtran@acm.org</a>.  The project's source code repository, wiki, and issue tracking can be found on the github page: <a href="https://github.com/lazy-bones/beautiful-data">https://github.com/lazy-bones/beautiful-data</a>.</p>
        
        <!-- we'll remove this as the team grow, right now it's a little sparse :-)
        <h3>beautiful-data Team</h3>
        <p> BD is not a one-person effort, instead it is built by a group data science enthusiasts.  The BD's team lead is <a href="http://pcwerk.com/~jtran/">John Tran</a>.  With active contributions from Eric Liao and <span style="font-weight:bold">you</span>.</p>
        -->
        
      </div>
    </div>

    <div id="footer">
      <div class="container">
        <p class="text-muted">beautiful-data is released under the <a href="https://www.apache.org/licenses/LICENSE-2.0.html">Apache 2.0 License</a></p>
      </div>
 